### ISSUE TITLE
Binary flagged by Windows Defender

### ISSUE THREAD

**Issue by cessnahat** [justinshannon/faa-mva-to-sector-file#1]
[This file](https://github.com/justinshannon/faa-mva-to-sector-file/releases/download/v1.0.1/v1.0.1.zip) (v1.0.1 GitHub release) gets flagged by Windows Defender as a trojan.

Windows error message:
> ![error msg](https://i.ibb.co/mRLZ898/flag.png)

**Comment by justinshannon** [comment]
It's a false positive from Windows Defender (my computer also flagged it when I downloaded it from the GH release section). Windows sees it as an "unknown" command line tool and flags it as malicious.
